# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the vLLM project
import glob
import itertools
import os
import platform
import subprocess
import sys

import jinja2

ARCHS = []
SUPPORT_FP8 = False
SUPPORT_SM75 = False
SUPPORT_SM80 = False
for arch in sys.argv[1].split(","):
    arch = arch[: arch.index(".") + 2].replace(".", "")
    arch = int(arch)
    # only SM89 and SM120 fully support
    # mma.sync.aligned.m16n8k32.row.col.f32.e4m3.e4m3.f32.
    # SM90 and SM100 can use this PTX, but it’s simulated
    # with FP16 MMA, so it cannot achieve any acceleration.
    if arch in [89, 120]:
        SUPPORT_FP8 = True
    if arch >= 80:
        SUPPORT_SM80 = True
    if arch == 75:
        SUPPORT_SM75 = True

FILE_HEAD_COMMENT = """
// auto generated by generate_kernels.py
// clang-format off
""".lstrip()

FILE_HEAD = (
    FILE_HEAD_COMMENT
    + """
#include "kernel.h"
#include "marlin_template.h"

namespace MARLIN_NAMESPACE_NAME {
"""
)

TEMPLATE = (
    "template __global__ void Marlin<"
    "{{a_type_id}}, "
    "{{b_type_id}}, "
    "{{c_type_id}}, "
    "{{s_type_id}}, "
    "{{threads}}, "
    "{{thread_m_blocks}}, "
    "{{thread_n_blocks}}, "
    "{{thread_k_blocks}}, "
    "{{m_block_size_8}}, "
    "{{stages}}, "
    "{{group_blocks}}, "
    "{{is_zp_float}}>"
    "( MARLIN_KERNEL_PARAMS );"
)

THREAD_CONFIGS = [(128, 128, 256), (64, 256, 256), (64, 128, 128), (128, 64, 128)]

THREAD_M_BLOCKS = [0.5, 1, 2, 3, 4]

QUANT_CONFIGS = [
    # AWQ-INT4
    {
        "b_type": "kU4",
        "thread_configs": THREAD_CONFIGS,
        "thread_m_blocks": THREAD_M_BLOCKS,
        "group_blocks": [-1, 2, 4, 8],
    },
    # GPTQ-INT4
    {
        "b_type": "kU4B8",
        "thread_configs": THREAD_CONFIGS,
        "thread_m_blocks": THREAD_M_BLOCKS,
        "group_blocks": [-1, 0, 2, 4, 8],
    },
    # GPTQ-INT8
    {
        "b_type": "kU8B128",
        "thread_configs": THREAD_CONFIGS,
        "thread_m_blocks": THREAD_M_BLOCKS,
        "group_blocks": [-1, 0, 2, 4, 8],
    },
    # FP8
    {
        "b_type": "kFE4M3fn",
        "thread_configs": THREAD_CONFIGS,
        "thread_m_blocks": THREAD_M_BLOCKS,
        "group_blocks": [-1, 8],
    },
    # NVFP4
    {
        "b_type": "kFE2M1f",
        "s_type": "kFE4M3fn",
        "thread_configs": THREAD_CONFIGS,
        "thread_m_blocks": THREAD_M_BLOCKS,
        "group_blocks": [1],
    },
    # MXFP4
    {
        "a_type": ["kBFloat16"],
        "b_type": "kFE2M1f",
        "s_type": "kFE8M0fnu",
        "thread_configs": THREAD_CONFIGS,
        "thread_m_blocks": THREAD_M_BLOCKS,
        "group_blocks": [2],
    },
    # MXFP8
    {
        "a_type": ["kBFloat16"],
        "b_type": "kFE4M3fn",
        "s_type": "kFE8M0fnu",
        "thread_configs": THREAD_CONFIGS,
        "thread_m_blocks": THREAD_M_BLOCKS,
        "group_blocks": [2],
    },
    # AWQ-INT4 with INT8 activation
    {
        "a_type": ["kS8"],
        "b_type": "kU4",
        "thread_configs": THREAD_CONFIGS,
        "thread_m_blocks": [1, 2, 3, 4],
        "group_blocks": [-1, 2, 4, 8],
    },
    # GPTQ-INT4 with INT8 activation
    {
        "a_type": ["kS8"],
        "b_type": "kU4B8",
        "thread_configs": THREAD_CONFIGS,
        "thread_m_blocks": [1, 2, 3, 4],
        "group_blocks": [-1, 2, 4, 8],
    },
    # GPTQ-INT4 with FP8 activation
    {
        "a_type": ["kFE4M3fn"],
        "b_type": "kU4B8",
        "thread_configs": THREAD_CONFIGS,
        "thread_m_blocks": [1, 2, 3, 4],
        "group_blocks": [-1, 2, 4, 8],
    },
    # AWQ-INT4 with FP8 activation
    {
        "a_type": ["kFE4M3fn"],
        "b_type": "kU4",
        "thread_configs": THREAD_CONFIGS,
        "thread_m_blocks": [1, 2, 3, 4],
        "group_blocks": [-1, 2, 4, 8],
    },
    # MXFP4 with FP8 activation
    {
        "a_type": ["kFE4M3fn"],
        "b_type": "kFE2M1f",
        "c_type": ["kBFloat16"],
        "s_type": "kFE8M0fnu",
        "thread_configs": THREAD_CONFIGS,
        "thread_m_blocks": [1, 2, 3, 4],
        "group_blocks": [2],
    },
]

RM_COMMAND = ["cmd.exe", "/C", "del", "/F"] if platform.system() == "Windows" else ["rm", "-f"]

# Header for kernel_selector.h: defines the KernelKey struct and hash,
# then opens the unordered_map initializer.
# Using long long for the type-id fields because vllm::ScalarType::id()
# returns a 64-bit value; the remaining fields are small integers / bools.
KERNEL_SELECTOR_MAP_HEAD = """\
{
  struct KernelKey {
    long long a, b, c, s;
    int threads, tm, tn, tk;
    bool msz8, izpf;
    int stages, gb;
    bool operator==(const KernelKey& o) const noexcept {
      return a==o.a && b==o.b && c==o.c && s==o.s &&
             threads==o.threads && tm==o.tm && tn==o.tn && tk==o.tk &&
             msz8==o.msz8 && izpf==o.izpf && stages==o.stages && gb==o.gb;
    }
  };
  struct KernelKeyHash {
    std::size_t operator()(const KernelKey& k) const noexcept {
      std::size_t h = 2166136261u;
      auto mix = [&](std::size_t v){ h ^= v; h *= 16777619u; };
      mix(static_cast<std::size_t>(k.a)); mix(static_cast<std::size_t>(k.b));
      mix(static_cast<std::size_t>(k.c)); mix(static_cast<std::size_t>(k.s));
      mix(static_cast<std::size_t>(k.threads));
      mix(static_cast<std::size_t>(k.tm)); mix(static_cast<std::size_t>(k.tn));
      mix(static_cast<std::size_t>(k.tk));
      mix(static_cast<std::size_t>(k.msz8)); mix(static_cast<std::size_t>(k.izpf));
      mix(static_cast<std::size_t>(k.stages));
      mix(static_cast<std::size_t>(k.gb + 128));
      return h;
    }
  };

  static const std::unordered_map<KernelKey, MarlinFuncPtr, KernelKeyHash> kernel_map = {
"""

# Footer: closes the map, then does the fp8 guard + lookup.
KERNEL_SELECTOR_MAP_FOOT = """\
  };

  if (a_type == vllm::kFE4M3fn) {
    TORCH_CHECK(false, "marlin kernel with fp8 activation is not built.");
  } else {
    KernelKey key{
      a_type.id(), b_type.id(), c_type.id(), s_type.id(),
      threads, thread_m_blocks, thread_n_blocks, thread_k_blocks,
      m_block_size_8, is_zp_float, stages, group_blocks
    };
    auto it = kernel_map.find(key);
    if (it != kernel_map.end()) kernel = it->second;
  }
}
"""

# Footer used when FP8 IS supported (no TORCH_CHECK guard needed).
KERNEL_SELECTOR_MAP_FOOT_FP8 = """\
  };

  {
    KernelKey key{
      a_type.id(), b_type.id(), c_type.id(), s_type.id(),
      threads, thread_m_blocks, thread_n_blocks, thread_k_blocks,
      m_block_size_8, is_zp_float, stages, group_blocks
    };
    auto it = kernel_map.find(key);
    if (it != kernel_map.end()) kernel = it->second;
  }
}
"""

# One map entry line.  All fields except the Marlin<> instantiation are
# known at generation time so we can emit integer literals directly.
KERNEL_SELECTOR_ENTRY_TEMPLATE = (
    "    {{KernelKey{{"
    "{a_type_id}, {b_type_id}, {c_type_id}, {s_type_id}, "
    "{threads}, {thread_m_blocks}, {thread_n_blocks}, {thread_k_blocks}, "
    "{m_block_size_8}, {is_zp_float}, {stages}, {group_blocks}"
    "}}, "
    "Marlin<"
    "{a_type_id}, {b_type_id}, {c_type_id}, {s_type_id}, "
    "{threads}, {thread_m_blocks}, {thread_n_blocks}, {thread_k_blocks}, "
    "{m_block_size_8}, {stages}, {group_blocks}, {is_zp_float}"
    ">}}{comma}\n"
)


def remove_old_kernels():
    for filename in glob.glob(os.path.dirname(__file__) + "/*kernel_*.cu"):
        subprocess.call(RM_COMMAND + [filename])

    filename = os.path.dirname(__file__) + "/kernel_selector.h"
    subprocess.call(RM_COMMAND + [filename])


def generate_new_kernels():
    result_dict = {}
    sm_75_result_dict = {}

    for quant_config in QUANT_CONFIGS:
        c_types = quant_config.get("c_type", ["kFloat16", "kBFloat16"])
        a_types = quant_config.get("a_type", ["kFloat16", "kBFloat16"])
        b_type = quant_config["b_type"]
        is_zp_float = quant_config.get("is_zp_float", False)
        all_group_blocks = quant_config["group_blocks"]
        all_m_blocks = quant_config["thread_m_blocks"]
        all_thread_configs = quant_config["thread_configs"]

        for a_type, c_type in itertools.product(a_types, c_types):
            if not SUPPORT_FP8 and a_type == "kFE4M3fn":
                continue
            if "16" in a_type and "16" in c_type and a_type != c_type:
                continue
            s_type = quant_config.get("s_type", c_type)
            if (a_type, b_type, c_type) not in result_dict:
                result_dict[(a_type, b_type, c_type)] = []
                if a_type in ["kFloat16", "kS8"] and c_type == "kFloat16":
                    sm_75_result_dict[(a_type, b_type, c_type)] = []

            for group_blocks, m_blocks, thread_configs in itertools.product(
                all_group_blocks, all_m_blocks, all_thread_configs
            ):
                thread_k, thread_n, threads = thread_configs

                if threads == 256:
                    # for small batch (m_blocks == 1),
                    #     we only need (128, 128, 256)
                    # for large batch (m_blocks > 1),
                    #     we only need (64, 256, 256)
                    if m_blocks <= 1 and (thread_k, thread_n) != (128, 128):
                        continue
                    if m_blocks > 1 and (thread_k, thread_n) != (64, 256):
                        continue

                config = {
                    "threads": threads,
                    "s_type": s_type,
                    "thread_m_blocks": max(m_blocks, 1),
                    "thread_k_blocks": thread_k // 16,
                    "thread_n_blocks": thread_n // 16,
                    "m_block_size_8": "true" if m_blocks == 0.5 else "false",
                    "stages": 4,
                    "group_blocks": group_blocks,
                    "is_zp_float": "true" if is_zp_float else "false",
                }

                if SUPPORT_SM80:
                    result_dict[(a_type, b_type, c_type)].append(config)
                if (a_type, b_type, c_type) in sm_75_result_dict and SUPPORT_SM75:
                    config_sm75 = config.copy()
                    config_sm75["stages"] = 2
                    sm_75_result_dict[(a_type, b_type, c_type)].append(config_sm75)

    # ------------------------------------------------------------------ #
    # Collect every (a_type, b_type, c_type, config) entry we will need   #
    # for the kernel_selector.h map.                                      #
    # ------------------------------------------------------------------ #
    all_entries = []  # list of (a_type, b_type, c_type, config) tuples

    for result_dict_tmp in [result_dict, sm_75_result_dict]:
        for (a_type, b_type, c_type), config_list in result_dict_tmp.items():
            all_template_str_list = []
            if not config_list:
                continue
            for config in config_list:
                all_entries.append((a_type, b_type, c_type, config))

                s_type = config["s_type"]
                template_str = jinja2.Template(TEMPLATE).render(
                    a_type_id=f"vllm::{a_type}.id()",
                    b_type_id=f"vllm::{b_type}.id()",
                    c_type_id=f"vllm::{c_type}.id()",
                    s_type_id=f"vllm::{s_type}.id()",
                    **config,
                )
                all_template_str_list.append(template_str)

            file_content = FILE_HEAD + "\n\n"
            file_content += "\n\n".join(all_template_str_list) + "\n\n}\n"
            if a_type == "kFE4M3fn":
                filename = f"sm89_kernel_{a_type[1:]}_{b_type[1:]}_{c_type[1:]}.cu"
            elif result_dict_tmp is sm_75_result_dict:
                filename = f"sm75_kernel_{a_type[1:]}_{b_type[1:]}_{c_type[1:]}.cu"
            else:
                filename = f"sm80_kernel_{a_type[1:]}_{b_type[1:]}_{c_type[1:]}.cu"

            filename = filename.lower()

            with open(os.path.join(os.path.dirname(__file__), filename), "w") as f:
                f.write(file_content)

    # ------------------------------------------------------------------ #
    # Write kernel_selector.h as an unordered_map lookup to avoid the    #
    # MSVC C1061 "blocks too deeply nested" error that the old            #
    # if/else-if chain triggered.                                         #
    # ------------------------------------------------------------------ #
    kernel_selector_str = FILE_HEAD_COMMENT
    kernel_selector_str += KERNEL_SELECTOR_MAP_HEAD

    for idx, (a_type, b_type, c_type, config) in enumerate(all_entries):
        s_type = config["s_type"]
        comma = "," if idx < len(all_entries) - 1 else ""
        kernel_selector_str += KERNEL_SELECTOR_ENTRY_TEMPLATE.format(
            a_type_id=f"vllm::{a_type}.id()",
            b_type_id=f"vllm::{b_type}.id()",
            c_type_id=f"vllm::{c_type}.id()",
            s_type_id=f"vllm::{s_type}.id()",
            threads=config["threads"],
            thread_m_blocks=int(config["thread_m_blocks"]),
            thread_n_blocks=config["thread_n_blocks"],
            thread_k_blocks=config["thread_k_blocks"],
            m_block_size_8=config["m_block_size_8"],
            stages=config["stages"],
            group_blocks=config["group_blocks"],
            is_zp_float=config["is_zp_float"],
            comma=comma,
        )

    if SUPPORT_FP8:
        kernel_selector_str += KERNEL_SELECTOR_MAP_FOOT_FP8
    else:
        kernel_selector_str += KERNEL_SELECTOR_MAP_FOOT

    with open(os.path.join(os.path.dirname(__file__), "kernel_selector.h"), "w") as f:
        f.write(kernel_selector_str)


if __name__ == "__main__":
    remove_old_kernels()
    generate_new_kernels()
